<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('municipios')->insert(['munic_desc' => 'SANDINO', 'prov_id' =>1]);
         DB::table('municipios')->insert(['munic_desc' => 'MANTUA', 'prov_id' =>1]);
         DB::table('municipios')->insert(['munic_desc' => 'MINAS DE MATAHAMBRE', 'prov_id' =>1]);
         DB::table('municipios')->insert(['munic_desc' => 'VINALES', 'prov_id' =>1]);
         DB::table('municipios')->insert(['munic_desc' => 'LA PALMA', 'prov_id' =>1]);
         DB::table('municipios')->insert(['munic_desc' => 'LOS PALACIOS', 'prov_id' =>1]);
         DB::table('municipios')->insert(['munic_desc' => 'CONSOLACION DEL SUR', 'prov_id' =>1]);
         DB::table('municipios')->insert(['munic_desc' => 'PINAR DEL RIO', 'prov_id' =>1]);
         DB::table('municipios')->insert(['munic_desc' => 'SAN LUIS', 'prov_id' =>1]);
         DB::table('municipios')->insert(['munic_desc' => 'SAN JUAN Y MARTINEZ', 'prov_id' =>1]);
         DB::table('municipios')->insert(['munic_desc' => 'GUANE', 'prov_id' =>1]);
         DB::table('municipios')->insert(['munic_desc' => 'BAHIA HONDA', 'prov_id' =>2]);
         DB::table('municipios')->insert(['munic_desc' => 'MARIEL', 'prov_id' =>2]);
         DB::table('municipios')->insert(['munic_desc' => 'GUANAJAY', 'prov_id' =>2]);
         DB::table('municipios')->insert(['munic_desc' => 'CAIMITO', 'prov_id' =>2]);
         DB::table('municipios')->insert(['munic_desc' => 'BAUTA', 'prov_id' =>2]);
         DB::table('municipios')->insert(['munic_desc' => 'SAN ANTONIO DE LOS BANOS', 'prov_id' =>2]);
         DB::table('municipios')->insert(['munic_desc' => 'GUIRA DE MELENA', 'prov_id' =>2]);
         DB::table('municipios')->insert(['munic_desc' => 'ALQUIZAR', 'prov_id' =>2]);
         DB::table('municipios')->insert(['munic_desc' => 'ARTEMISA', 'prov_id' =>2]);
         DB::table('municipios')->insert(['munic_desc' => 'CANDELARIA', 'prov_id' =>2]);
         DB::table('municipios')->insert(['munic_desc' => 'SAN CRISTOBAL', 'prov_id' =>2]);
         DB::table('municipios')->insert(['munic_desc' => 'PLAYA', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'PLAZA DE LA REVOLUCION', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'CENTRO HABANA', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'LA HABANA VIEJA', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'REGLA', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'LA HABANA DEL ESTE', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'GUANABACOA', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'SAN MIGUEL DEL PADRON', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'DIEZ DE OCTUBRE', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'CERRO', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'MARIANAO', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'LA LISA', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'BOYEROS', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'ARROYO NARANJO', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'COTORRO', 'prov_id' =>3]);
         DB::table('municipios')->insert(['munic_desc' => 'BEJUCAL', 'prov_id' =>4]);
         DB::table('municipios')->insert(['munic_desc' => 'SAN JOSE DE LAS LAJAS', 'prov_id' =>4]);
         DB::table('municipios')->insert(['munic_desc' => 'JARUCO', 'prov_id' =>4]);
         DB::table('municipios')->insert(['munic_desc' => 'SANTA CRUZ DEL NORTE', 'prov_id' =>4]);
         DB::table('municipios')->insert(['munic_desc' => 'MADRUGA', 'prov_id' =>4]);
         DB::table('municipios')->insert(['munic_desc' => 'NUEVA PAZ', 'prov_id' =>4]);
         DB::table('municipios')->insert(['munic_desc' => 'SAN NICOLAS', 'prov_id' =>4]);
         DB::table('municipios')->insert(['munic_desc' => 'GUINES', 'prov_id' =>4]);
         DB::table('municipios')->insert(['munic_desc' => 'MELENA DEL SUR', 'prov_id' =>4]);
         DB::table('municipios')->insert(['munic_desc' => 'BATABANO', 'prov_id' =>4]);
         DB::table('municipios')->insert(['munic_desc' => 'QUIVICAN', 'prov_id' =>4]);
         DB::table('municipios')->insert(['munic_desc' => 'MATANZAS', 'prov_id' =>5]);
         DB::table('municipios')->insert(['munic_desc' => 'CARDENAS ', 'prov_id' =>5]);
         DB::table('municipios')->insert(['munic_desc' => 'MARTI', 'prov_id' =>5]);
         DB::table('municipios')->insert(['munic_desc' => 'COLON', 'prov_id' =>5]);
         DB::table('municipios')->insert(['munic_desc' => 'PERICO', 'prov_id' =>5]);
         DB::table('municipios')->insert(['munic_desc' => 'JOVELLANOS', 'prov_id' =>5]);
         DB::table('municipios')->insert(['munic_desc' => 'PEDRO BETANCOURT', 'prov_id' =>5]);
         DB::table('municipios')->insert(['munic_desc' => 'LIMONAR', 'prov_id' =>5]);
         DB::table('municipios')->insert(['munic_desc' => 'UNION DE REYES', 'prov_id' =>5]);
         DB::table('municipios')->insert(['munic_desc' => 'CIENAGA DE ZAPATA', 'prov_id' =>5]);
         DB::table('municipios')->insert(['munic_desc' => 'JAGUEY GRANDE', 'prov_id' =>5]);
         DB::table('municipios')->insert(['munic_desc' => 'CALIMETE', 'prov_id' =>5]);
         DB::table('municipios')->insert(['munic_desc' => 'LOS ARABOS', 'prov_id' =>5]);
         DB::table('municipios')->insert(['munic_desc' => 'CORRALILLO', 'prov_id' =>6]);
         DB::table('municipios')->insert(['munic_desc' => 'QUEMADO DE GUINES', 'prov_id' =>6]);
         DB::table('municipios')->insert(['munic_desc' => 'SAGUA LA GRANDE', 'prov_id' =>6]);
         DB::table('municipios')->insert(['munic_desc' => 'ENCRUCIJADA', 'prov_id' =>6]);
         DB::table('municipios')->insert(['munic_desc' => 'CAMAJUANI', 'prov_id' =>6]);
         DB::table('municipios')->insert(['munic_desc' => 'CAIBARIEN', 'prov_id' =>6]);
         DB::table('municipios')->insert(['munic_desc' => 'REMEDIOS', 'prov_id' =>6]);
         DB::table('municipios')->insert(['munic_desc' => 'PLACETAS', 'prov_id' =>6]);
         DB::table('municipios')->insert(['munic_desc' => 'SANTA CLARA', 'prov_id' =>6]);
         DB::table('municipios')->insert(['munic_desc' => 'CIFUENTES', 'prov_id' =>6]);
         DB::table('municipios')->insert(['munic_desc' => 'SANTO DOMINGO', 'prov_id' =>6]);
         DB::table('municipios')->insert(['munic_desc' => 'RANCHUELO', 'prov_id' =>6]);
         DB::table('municipios')->insert(['munic_desc' => 'MANICARAGUA', 'prov_id' =>6]);
         DB::table('municipios')->insert(['munic_desc' => 'AGUADA DE PASAJEROS', 'prov_id' =>7]);
         DB::table('municipios')->insert(['munic_desc' => 'RODAS', 'prov_id' =>7]);
         DB::table('municipios')->insert(['munic_desc' => 'PALMIRA', 'prov_id' =>7]);
         DB::table('municipios')->insert(['munic_desc' => 'LAJAS', 'prov_id' =>7]);
         DB::table('municipios')->insert(['munic_desc' => 'CRUCES', 'prov_id' =>7]);
         DB::table('municipios')->insert(['munic_desc' => 'CUMANAYAGUA', 'prov_id' =>7]);
         DB::table('municipios')->insert(['munic_desc' => 'CIENFUEGOS', 'prov_id' =>7]);
         DB::table('municipios')->insert(['munic_desc' => 'ABREUS', 'prov_id' =>7]);
         DB::table('municipios')->insert(['munic_desc' => 'YAGUAJAY', 'prov_id' =>8]);
         DB::table('municipios')->insert(['munic_desc' => 'JATIBONICO', 'prov_id' =>8]);
         DB::table('municipios')->insert(['munic_desc' => 'TAGUASCO', 'prov_id' =>8]);
         DB::table('municipios')->insert(['munic_desc' => 'CABAIGUAN', 'prov_id' =>8]);
         DB::table('municipios')->insert(['munic_desc' => 'FOMENTO', 'prov_id' =>8]);
         DB::table('municipios')->insert(['munic_desc' => 'TRINIDAD', 'prov_id' =>8]);
         DB::table('municipios')->insert(['munic_desc' => 'SANCTI SPIRITUS', 'prov_id' =>8]);
         DB::table('municipios')->insert(['munic_desc' => 'LA SIERPE', 'prov_id' =>8]);
         DB::table('municipios')->insert(['munic_desc' => 'CHAMBAS', 'prov_id' =>9]);
         DB::table('municipios')->insert(['munic_desc' => 'MORON', 'prov_id' =>9]);
         DB::table('municipios')->insert(['munic_desc' => 'BOLIVIA', 'prov_id' =>9]);
         DB::table('municipios')->insert(['munic_desc' => 'PRIMERO DE ENERO', 'prov_id' =>9]);
         DB::table('municipios')->insert(['munic_desc' => 'CIRO REDONDO', 'prov_id' =>9]);
         DB::table('municipios')->insert(['munic_desc' => 'FLORENCIA', 'prov_id' =>9]);
         DB::table('municipios')->insert(['munic_desc' => 'MAJAGUA', 'prov_id' =>9]);
         DB::table('municipios')->insert(['munic_desc' => 'CIEGO DE AVILA', 'prov_id' =>9]);
         DB::table('municipios')->insert(['munic_desc' => 'VENEZUELA', 'prov_id' =>9]);
         DB::table('municipios')->insert(['munic_desc' => 'BARAGUA', 'prov_id' =>9]);
         DB::table('municipios')->insert(['munic_desc' => 'CARLOS MANUEL DE CESPEDES', 'prov_id' =>10]);
         DB::table('municipios')->insert(['munic_desc' => 'ESMERALDA', 'prov_id' =>10]);
         DB::table('municipios')->insert(['munic_desc' => 'SIERRA DE CUBITAS', 'prov_id' =>10]);
         DB::table('municipios')->insert(['munic_desc' => 'MINAS', 'prov_id' =>10]);
         DB::table('municipios')->insert(['munic_desc' => 'NUEVITAS', 'prov_id' =>10]);
         DB::table('municipios')->insert(['munic_desc' => 'GUAIMARO', 'prov_id' =>10]);
         DB::table('municipios')->insert(['munic_desc' => 'SIBANICU', 'prov_id' =>10]);
         DB::table('municipios')->insert(['munic_desc' => 'CAMAGUEY', 'prov_id' =>10]);
         DB::table('municipios')->insert(['munic_desc' => 'FLORIDA', 'prov_id' =>10]);
         DB::table('municipios')->insert(['munic_desc' => 'VERTIENTES', 'prov_id' =>10]);
         DB::table('municipios')->insert(['munic_desc' => 'JIMAGUAYU', 'prov_id' =>10]);
         DB::table('municipios')->insert(['munic_desc' => 'NAJASA', 'prov_id' =>10]);
         DB::table('municipios')->insert(['munic_desc' => 'SANTA CRUZ DEL SUR', 'prov_id' =>10]);
         DB::table('municipios')->insert(['munic_desc' => 'MANATI', 'prov_id' =>11]);
         DB::table('municipios')->insert(['munic_desc' => 'PUERTO PADRE', 'prov_id' =>11]);
         DB::table('municipios')->insert(['munic_desc' => 'JESUS MENENDEZ', 'prov_id' =>11]);
         DB::table('municipios')->insert(['munic_desc' => 'MAJIBACOA', 'prov_id' =>11]);
         DB::table('municipios')->insert(['munic_desc' => 'LAS TUNAS', 'prov_id' =>11]);
         DB::table('municipios')->insert(['munic_desc' => 'JOBABO', 'prov_id' =>11]);
         DB::table('municipios')->insert(['munic_desc' => 'COLOMBIA', 'prov_id' =>11]);
         DB::table('municipios')->insert(['munic_desc' => 'AMANCIO', 'prov_id' =>11]);
         DB::table('municipios')->insert(['munic_desc' => 'GIBARA', 'prov_id' =>12]);
         DB::table('municipios')->insert(['munic_desc' => 'RAFAEL FREYRE', 'prov_id' =>12]);
         DB::table('municipios')->insert(['munic_desc' => 'BANES', 'prov_id' =>12]);
         DB::table('municipios')->insert(['munic_desc' => 'ANTILLA', 'prov_id' =>12]);
         DB::table('municipios')->insert(['munic_desc' => 'BAGUANOS', 'prov_id' =>12]);
         DB::table('municipios')->insert(['munic_desc' => 'HOLGUIN', 'prov_id' =>12]);
         DB::table('municipios')->insert(['munic_desc' => 'CALIXTO GARCIA', 'prov_id' =>12]);
         DB::table('municipios')->insert(['munic_desc' => 'CACOCUM', 'prov_id' =>12]);
         DB::table('municipios')->insert(['munic_desc' => 'URBANO NORIS', 'prov_id' =>12]);
         DB::table('municipios')->insert(['munic_desc' => 'CUETO', 'prov_id' =>12]);
         DB::table('municipios')->insert(['munic_desc' => 'MAYARI', 'prov_id' =>12]);
         DB::table('municipios')->insert(['munic_desc' => 'FRANK PAIS', 'prov_id' =>12]);
         DB::table('municipios')->insert(['munic_desc' => 'SAGUA DE TANAMO', 'prov_id' =>12]);
         DB::table('municipios')->insert(['munic_desc' => 'MOA', 'prov_id' =>12]);
         DB::table('municipios')->insert(['munic_desc' => 'RIO CAUTO', 'prov_id' =>13]);
         DB::table('municipios')->insert(['munic_desc' => 'CAUTO CRISTO', 'prov_id' =>13]);
         DB::table('municipios')->insert(['munic_desc' => 'JIGUANI', 'prov_id' =>13]);
         DB::table('municipios')->insert(['munic_desc' => 'BAYAMO', 'prov_id' =>13]);
         DB::table('municipios')->insert(['munic_desc' => 'YARA', 'prov_id' =>13]);
         DB::table('municipios')->insert(['munic_desc' => 'MANZANILLO', 'prov_id' =>13]);
         DB::table('municipios')->insert(['munic_desc' => 'CAMPECHUELA', 'prov_id' =>13]);
         DB::table('municipios')->insert(['munic_desc' => 'MEDIA LUNA', 'prov_id' =>13]);
         DB::table('municipios')->insert(['munic_desc' => 'NIQUERO', 'prov_id' =>13]);
         DB::table('municipios')->insert(['munic_desc' => 'PILON', 'prov_id' =>13]);
         DB::table('municipios')->insert(['munic_desc' => 'BARTOLOME MASO', 'prov_id' =>13]);
         DB::table('municipios')->insert(['munic_desc' => 'BUEY ARRIBA', 'prov_id' =>13]);
         DB::table('municipios')->insert(['munic_desc' => 'GUISA', 'prov_id' =>13]);
         DB::table('municipios')->insert(['munic_desc' => 'CONTRAMAESTRE', 'prov_id' =>14]);
         DB::table('municipios')->insert(['munic_desc' => 'MELLA', 'prov_id' =>14]);
         DB::table('municipios')->insert(['munic_desc' => 'SAN LUIS', 'prov_id' =>14]);
         DB::table('municipios')->insert(['munic_desc' => 'SEGUNDO FRENTE', 'prov_id' =>14]);
         DB::table('municipios')->insert(['munic_desc' => 'SONGO - LA MAYA', 'prov_id' =>14]);
         DB::table('municipios')->insert(['munic_desc' => 'SANTIAGO DE CUBA', 'prov_id' =>14]);
         DB::table('municipios')->insert(['munic_desc' => 'PALMA SORIANO', 'prov_id' =>14]);
         DB::table('municipios')->insert(['munic_desc' => 'TERCER FRENTE', 'prov_id' =>14]);
         DB::table('municipios')->insert(['munic_desc' => 'GUAMA', 'prov_id' =>14]);
         DB::table('municipios')->insert(['munic_desc' => 'EL SALVADOR', 'prov_id' =>15]);
         DB::table('municipios')->insert(['munic_desc' => 'MANUEL TAMES', 'prov_id' =>15]);
         DB::table('municipios')->insert(['munic_desc' => 'YATERAS', 'prov_id' =>15]);
         DB::table('municipios')->insert(['munic_desc' => 'BARACOA', 'prov_id' =>15]);
         DB::table('municipios')->insert(['munic_desc' => 'MAISI', 'prov_id' =>15]);
         DB::table('municipios')->insert(['munic_desc' => 'IMIAS', 'prov_id' =>15]);
         DB::table('municipios')->insert(['munic_desc' => 'SAN ANTONIO DEL SUR', 'prov_id' =>15]);
         DB::table('municipios')->insert(['munic_desc' => 'CAIMANERA', 'prov_id' =>15]);
         DB::table('municipios')->insert(['munic_desc' => 'GUANTANAMO', 'prov_id' =>15]);
         DB::table('municipios')->insert(['munic_desc' => 'NICETO PEREZ', 'prov_id' =>15]);
    }}


